QBShared = QBShared or {}
QBShared.VehicleHashes = {}

QBShared.Vehicles = {
	--- Compacts
	['ttrs'] = {
		['name'] = 'Audi ttrs',
		['brand'] = '',
		['model'] = 'ttrs',
		['price'] = 20000,
		['category'] = 'compacts',
		['hash'] = `ttrs`,
		['shop'] = 'pdm',
	},
	['m2'] = {
		['name'] = 'BMW M2',
		['brand'] = '',
		['model'] = 'M2',
		['price'] = 55000,
		['category'] = 'compacts',
		['hash'] = `M2`,
		['shop'] = 'pdm',
	},
	['sandero'] = {
		['name'] = 'Dacia sandero',
		['brand'] = '',
		['model'] = 'sandero',
		['price'] = 10000,
		['category'] = 'compacts',
		['hash'] = `sandero`,
		['shop'] = 'pdm',
	},
	['ap2'] = {
		['name'] = 'Honda ap2',
		['brand'] = '',
		['model'] = 'ap2',
		['price'] = 40000,
		['category'] = 'compacts',
		['hash'] = `ap2`,
		['shop'] = 'pdm',
	},
	['ep3'] = {
		['name'] = 'Honda civic ep3',
		['brand'] = '',
		['model'] = 'ep3',
		['price'] = 15000,
		['category'] = 'compacts',
		['hash'] = `ep3`,
		['shop'] = 'pdm',
	},
	['maj350'] = {
		['name'] = 'Nissan 350z',
		['brand'] = '',
		['model'] = 'maj350',
		['price'] = 20000,
		['category'] = 'compacts',
		['hash'] = `maj350`,
		['shop'] = 'pdm',
	},
	--- Coupes

	['rs6'] = {
		['name'] = 'Audi rs6',
		['brand'] = '',
		['model'] = 'rs6',
		['price'] = 250000,
		['category'] = 'coupes',
		['hash'] = `rs6`,
		['shop'] = 'pdm',
	},
	['teslapd'] = {
		['name'] = 'Tesla PD',
		['brand'] = '',
		['model'] = 'teslapd',
		['price'] = 110000,
		['category'] = 'coupes',
		['hash'] = `teslapd`,
		['shop'] = 'pdm',
	},
	['taycan'] = {
		['name'] = 'Porsche Taycan',
		['brand'] = '',
		['model'] = 'taycan',
		['price'] = 150000,
		['category'] = 'coupes',
		['hash'] = `taycan`,
		['shop'] = 'pdm',
	},
	['e400'] = {
		['name'] = 'Mercedes Benz e400',
		['brand'] = '',
		['model'] = 'e400',
		['price'] = 175000,
		['category'] = 'coupes',
		['hash'] = `e400`,
		['shop'] = 'pdm',
	},
	['c6320'] = {
		['name'] = 'Mercedes AMG c63s',
		['brand'] = '',
		['model'] = 'c6320',
		['price'] = 170000,
		['category'] = 'coupes',
		['hash'] = `c6320`,
		['shop'] = 'pdm',
	},
	['mbc63'] = {
		['name'] = 'Mercedes c63 AMG',
		['brand'] = '',
		['model'] = 'mbc63',
		['price'] = 155000,
		['category'] = 'coupes',
		['hash'] = `mbc63`,
		['shop'] = 'pdm',
	},
	['ast'] = {
		['name'] = 'Aston martin',
		['brand'] = '',
		['model'] = 'ast',
		['price'] = 120000,
		['category'] = 'coupes',
		['hash'] = `ast`,
		['shop'] = 'pdm',
	},
	['fk8'] = {
		['name'] = 'Honda civic fk8',
		['brand'] = '',
		['model'] = 'fk8',
		['price'] = 45000,
		['category'] = 'coupes',
		['hash'] = `fk8`,
		['shop'] = 'pdm',
	},
		--- Cycles
	['bmx'] = {
		['name'] = 'BMX',
        ['brand'] = 'Bike',
		['model'] = 'bmx',
		['price'] = 160,
		['category'] = 'cycles',
		['hash'] = `bmx`,
		['shop'] = 'pdm',
	},
		--- Motorcycles
	['sanchez'] = {
		['name'] = 'Crossmotor',
		['brand'] = '',
		['model'] = 'sanchez',
		['price'] = 3700,
		['category'] = 'motorcycles',
		['hash'] = `sanchez`,
		['shop'] = 'pdm',
	},
        ['katana'] = {
		['name'] = 'Katana',
		['brand'] = '',
		['model'] = 'katana',
		['price'] = 22000,
		['category'] = 'motorcycles',
		['hash'] = `katana`,
		['shop'] = 'pdm',
	},
        ['flhxs_streetglide_special18'] = {
		['name'] = 'Acknod',
		['brand'] = '',
		['model'] = 'flhxs_streetglide_special18',
		['price'] = 40000,
		['category'] = 'motorcycles',
		['hash'] = `flhxs_streetglide_special18`,
		['shop'] = 'pdm',
	},
        ['bmws19'] = {
		['name'] = 'bmw s1000rr',
		['brand'] = '',
		['model'] = 'bmws19',
		['price'] = 40000,
		['category'] = 'motorcycles',
		['hash'] = `bmws19`,
		['shop'] = 'pdm',
	},
        ['vision'] = {
		['name'] = 'Vision scooter',
		['brand'] = '',
		['model'] = 'vision',
		['price'] = 4600,
		['category'] = 'motorcycles',
		['hash'] = `vision`,
		['shop'] = 'pdm',
	},
        ['zip'] = {
		['name'] = 'Zip scooter',
		['brand'] = '',
		['model'] = 'zip',
		['price'] = 6000,
		['category'] = 'motorcycles',
		['hash'] = `zip`,
		['shop'] = 'pdm',
	},
        ['xmax'] = {
		['name'] = 'Xmax scooter',
		['brand'] = '',
		['model'] = 'xmax',
		['price'] = 14000,
		['category'] = 'motorcycles',
		['hash'] = `xmax`,
		['shop'] = 'pdm',
	},
        ['vespa1'] = {
		['name'] = 'Vespa scooter',
		['brand'] = '',
		['model'] = 'vespa1',
		['price'] = 8000,
		['category'] = 'motorcycles',
		['hash'] = `vespa1`,
		['shop'] = 'pdm',
	},
        ['nrg'] = {
		['name'] = 'Nrg scooter',
		['brand'] = '',
		['model'] = 'nrg',
		['price'] = 5000,
		['category'] = 'motorcycles',
		['hash'] = `nrg`,
		['shop'] = 'pdm',
	},

		--- Muscle
       ['99viper'] = {
		['name'] = '99 Dodge Viper',
		['brand'] = '',
		['model'] = '99viper',
		['price'] = '55000',
		['category'] = 'muscle',
		['hash'] = `99viper`,
		['shop'] = 'pdm',
	},
	['demon'] = {
		['name'] = 'Dodge demon',
		['brand'] = '',
		['model'] = 'demon',
		['price'] = '130000',
		['category'] = 'muscle',
		['hash'] = `demon`,
		['shop'] = 'pdm',
	},
	['16charger'] = {
		['name'] = 'Dodge charger',
		['brand'] = '',
		['model'] = '16charger',
		['price'] = '90000',
		['category'] = 'muscle',
		['hash'] = `16charger`,
		['shop'] = 'pdm',
	},
	['camrs17'] = {
		['name'] = 'Camaro Rs17',
		['brand'] = '',
		['model'] = 'camrs17',
		['price'] = 75000,
		['category'] = 'muscle',
		['hash'] = `camrs17`,
		['shop'] = 'pdm',
	},
	['c7'] = {
		['name'] = 'Corvette c7',
		['brand'] = '',
		['model'] = 'c7',
		['price'] = 80000,
		['category'] = 'muscle',
		['hash'] = `c7`,
		['shop'] = 'pdm',
	},
	['stingray'] = {							
		['name'] = 'stingray',
		['brand'] = '',
		['model'] = 'stingray',
		['price'] = 160000,
		['category'] = 'muscle',
		['hash'] = `stingray`,
		['shop'] = 'pdm',
	},
	['corvettec5z06'] = {
		['name'] = 'Corvette c5',
		['brand'] = '',
		['model'] = 'corvettec5z06',
		['price'] = 35000,
		['category'] = 'muscle',
		['hash'] = `corvettec5z06`,
		['shop'] = 'pdm',
	},
	['czr1'] = {							--DLC
		['name'] = 'Chervrolet cr1',
		['brand'] = '',
		['model'] = 'czr1',
		['price'] = 35000,
		['category'] = 'muscle',
		['hash'] = `czr1`,
		['shop'] = 'pdm',
	},
	['chr20'] = {
		['name'] = 'Dodge Hellcat',
		['brand'] = '',
		['model'] = 'chr20',
		['price'] = 75000,
		['category'] = 'muscle',
		['hash'] = `chr20`,
		['shop'] = 'pdm',
	},
	['mustang50th'] = {
		['name'] = 'mustang50th',
		['brand'] = '',
		['model'] = 'mustang50th',
		['price'] = 85000,
		['category'] = 'muscle',
		['hash'] = `mustang50th`,
		['shop'] = 'pdm',
	},
		--- Off-Road
	['trx'] = {
		['name'] = 'Dodge ram',
		['brand'] = '',
		['price'] = 70000,
		['category'] = 'offroad',
		['model'] = 'trx',
		['hash'] = `trx`,
		['shop'] = 'pdm',
	},
	['x5e53'] = {
		['name'] = 'Bmw x5 e53',
		['brand'] = '',
		['price'] = 23000,
		['category'] = 'offroad',
		['model'] = 'x5e53',
		['hash'] = `x5e53`,
		['shop'] = 'pdm',
	},
	['jeep2012'] = {
		['name'] = 'Jeep Wrangler',
		['brand'] = '',
		['price'] = 110000,
		['category'] = 'offroad',
		['model'] = 'jeep2012',
		['hash'] = `jeep2012`,
		['shop'] = 'pdm',
	},
		--- SUVs
	['urus'] = {
		['name'] = 'Lamborghini urus',
		['brand'] = '',
		['model'] = 'urus',
		['price'] = 300000,
		['category'] = 'suvs',
		['hash'] = `urus`,
		['shop'] = 'pdm',
	},
	['amdbx'] = {
		['name'] = 'Aston Martin DBX',
		['brand'] = '',
		['model'] = 'amdbx',
		['price'] = 190000,
		['category'] = 'suvs',
		['hash'] = `amdbx`,
		['shop'] = 'pdm',
	},
	['q820'] = {
		['name'] = 'Audi Q8',
		['brand'] = '',
		['model'] = 'q820',
		['price'] = 95000,
		['category'] = 'suvs',
		['hash'] = `q820`,
		['shop'] = 'pdm',
	},
	['sq72016'] = {
		['name'] = 'Audi SQ7',
		['brand'] = '',
		['model'] = 'sq72016',
		['price'] = 75000,
		['category'] = 'suvs',
		['hash'] = `sq72016`,
		['shop'] = 'pdm',
	},
	['bbentayga'] = {
		['name'] = 'Bentley Bentayga',
		['brand'] = '',
		['model'] = 'bbentayga',
		['price'] = 140000,
		['category'] = 'suvs',
		['hash'] = `bbentayga`,
		['shop'] = 'pdm',
	},
			--- Sedans

	['m3e92'] = {
		['name'] = 'bmw m3 e92',
		['brand'] = '',
		['model'] = 'm3e92',
		['price'] = 30000,
		['category'] = 'sedans',
		['hash'] = `m3e92`,
		['shop'] = 'pdm',
	},
	['bmci'] = {
		['name'] = 'bmw m5 f90',
		['brand'] = '',
		['model'] = 'bmci',
		['price'] = 120000,
		['category'] = 'sedans',
		['hash'] = `bmci`,
		['shop'] = 'pdm',
	},
	['m3f80'] = {
		['name'] = 'bmw m3 f80',
		['brand'] = '',
		['model'] = 'm3f80',
		['price'] = 65000,
		['category'] = 'sedans',
		['hash'] = `m3f80`,
		['shop'] = 'pdm',
	},
	['m4f82'] = {
		['name'] = 'bmw m4 f82',
		['brand'] = '',
		['model'] = 'm4f82',
		['price'] = 65000,
		['category'] = 'sedans',
		['hash'] = `m4f82`,
		['shop'] = 'pdm',
	},
	['is350mod'] = {
		['name'] = 'lexus is 350',
		['brand'] = '',
		['model'] = 'is350mod',
		['price'] = 45000,
		['category'] = 'sedans',
		['hash'] = `is350mod`,
		['shop'] = 'pdm',
	},
		--- Sports
	['Bolide'] = {
		['name'] = 'Bolide',
		['brand'] = '',
		['model'] = 'Bolide',
		['price'] = 1,
		['category'] = 'sports',
		['hash'] = `Bolide`,
		['shop'] = 'luxury',
	},
		['m3e36'] = {
		['name'] = 'Bmw 1997 m3',
		['brand'] = '',
		['model'] = 'm3e36',
		['price'] = 35000,
		['category'] = 'sportsclassics',
		['hash'] = `m3e36`,
		['shop'] = 'pdm',
	},
		['g65'] = {
		['name'] = 'g65',
		['brand'] = '',
		['model'] = 'g65',
		['price'] = 1,
		['category'] = 'sports',
		['hash'] = `g65`,
		['shop'] = 'luxury',
	},
	['huracanst'] = {
		['name'] = 'huracanst',
		['brand'] = '',
		['model'] = 'huracanst',
		['price'] = 1,
		['category'] = 'sports',
		['hash'] = `huracanst`,
		['shop'] = 'luxury',
	},
	['schafter4'] = {
		['name'] = 'Schafter LWB',
		['brand'] = 'Benefactor',
		['model'] = 'schafter4',
		['price'] = 21000,
		['category'] = 'sports',
		['hash'] = `schafter4`,
		['shop'] = 'luxury',
	},
	['schlagen'] = {							--DLC
		['name'] = 'Schlagen GT',
		['brand'] = 'Benefactor',
		['model'] = 'schlagen',
		['price'] = 160000,
		['category'] = 'sports',
		['hash'] = `schlagen`,
		['shop'] = 'luxury',
	},
	['schwarzer'] = {
		['name'] = 'Schwartzer',
		['brand'] = 'Benefactor',
		['model'] = 'schwarzer',
		['price'] = 47000,
		['category'] = 'sports',
		['hash'] = `schwarzer`,
		['shop'] = 'luxury',
	},
		['seven70'] = {
		['name'] = 'Seven-70',
		['brand'] = 'Dewbauchee',
		['model'] = 'seven70',
		['price'] = 140000,
		['category'] = 'sports',
		['hash'] = `seven70`,
		['shop'] = 'luxury',
	},
	['specter'] = {
		['name'] = 'Specter',
		['brand'] = 'Dewbauchee',
		['model'] = 'specter',
		['price'] = 160000,
		['category'] = 'sports',
		['hash'] = `specter`,
		['shop'] = 'luxury',
	},
	['streiter'] = {
		['name'] = 'Streiter',
		['brand'] = 'Benefactor',
		['model'] = 'streiter',
		['price'] = 40000,
		['category'] = 'sports',
		['hash'] = `streiter`,
		['shop'] = 'luxury',
	},
	['sugoi'] = {
		['name'] = 'Sugoi',
		['brand'] = 'Dinka',
		['model'] = 'sugoi',
		['price'] = 85000,
		['category'] = 'sports',
		['hash'] = `sugoi`,
		['shop'] = 'luxury',
	},
	['sultan'] = {
		['name'] = 'Sultan',
		['brand'] = 'Karin',
		['model'] = 'sultan',
		['price'] = 50000,
		['category'] = 'sports',
		['hash'] = `sultan`,
		['shop'] = 'luxury',
	},
	['sultan2'] = {
		['name'] = 'Sultan Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan2',
		['price'] = 55000,
		['category'] = 'sports',
		['hash'] = `sultan2`,
		['shop'] = 'luxury',
	},
	['surano'] = {
		['name'] = 'Surano',
		['brand'] = ' Benefactor',
		['model'] = 'surano',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `surano`,
		['shop'] = 'luxury',
	},
		['tropos'] = {
		['name'] = 'Tropos Rallye',
		['brand'] = 'Lampadati',
		['model'] = 'tropos',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `tropos`,
		['shop'] = 'luxury',
	},
	['verlierer2'] = {
		['name'] = 'Verlierer',
		['brand'] = 'Bravado',
		['model'] = 'verlierer2',
		['price'] = 90500,
		['category'] = 'sports',
		['hash'] = `verlierer2`,
		['shop'] = 'luxury',
	},
	['vstr'] = {
		['name'] = 'V-STR',
		['brand'] = 'Albany',
		['model'] = 'vstr',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `vstr`,
		['shop'] = 'luxury',
	},
	['italirsx'] = {
		['name'] = 'Itali RSX',
		['brand'] = 'Progen',
		['model'] = 'italirsx',
		['price'] = 260000,
		['category'] = 'sports',
		['hash'] = `italirsx`,
		['shop'] = 'luxury',
	},
	['zr350'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'ZR350',
		['brand'] = 'Annis',
		['model'] = 'zr350',
		['price'] = 38000,
		['category'] = 'sports',
		['hash'] = `zr350`,
		['shop'] = 'luxury',
	},
	['calico'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Calico GTF',
		['brand'] = 'Karin',
		['model'] = 'calico',
		['price'] = 39000,
		['category'] = 'sports',
		['hash'] = `calico`,
		['shop'] = 'luxury',
	},
	['futo2'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Futo GTX',
		['brand'] = 'Karin',
		['model'] = 'futo2',
		['price'] = 39000,
		['category'] = 'sports',
		['hash'] = `futo2`,
		['shop'] = 'luxury',
	},
		['jester4'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Jester RR',
		['brand'] = 'Dinka',
		['model'] = 'jester4',
		['price'] = 240000,
		['category'] = 'sports',
		['hash'] = `jester4`,
		['shop'] = 'luxury',
	},
	['remus'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Remus',
		['brand'] = 'Annis',
		['model'] = 'remus',
		['price'] = 48000,
		['category'] = 'sports',
		['hash'] = `remus`,
		['shop'] = 'luxury',
	},
	['comet6'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Comet S2',
		['brand'] = 'Pfister',
		['model'] = 'comet6',
		['price'] = 230000,
		['category'] = 'sports',
		['hash'] = `comet6`,
		['shop'] = 'luxury',
	},
	['growler'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Growler',
		['brand'] = 'Pfister',
		['model'] = 'growler',
		['price'] = 205000,
		['category'] = 'sports',
		['hash'] = `growler`,
		['shop'] = 'luxury',
	},
	['vectre'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Emperor Vectre',
		['brand'] = 'Emperor',
		['model'] = 'vectre',
		['price'] = 80000,
		['category'] = 'sports',
		['hash'] = `vectre`,
		['shop'] = 'luxury',
	},
	['cypher'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Cypher',
		['brand'] = 'Ubermacht',
		['model'] = 'cypher',
		['price'] = 155000,
		['category'] = 'sports',
		['hash'] = `cypher`,
		['shop'] = 'luxury',
	},
	['sultan3'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'Sultan Classic Custom',
		['brand'] = 'Karin',
		['model'] = 'sultan3',
		['price'] = 56000,
		['category'] = 'sports',
		['hash'] = `sultan3`,
		['shop'] = 'luxury',
	},
	['rt3000'] = {							--DLC +set sv_enforceGameBuild 2372
		['name'] = 'RT3000',
		['brand'] = 'Dinka',
		['model'] = 'rt3000',
		['price'] = 65000,
		['category'] = 'sports',
		['hash'] = `rt3000`,
		['shop'] = 'luxury',
	},
	--- Sports Classic
	['s8d2'] = {
		['name'] = 'Audi s8 1998',
		['brand'] = '',
		['model'] = 's8d2',
		['price'] = 45000,
		['category'] = 'sportsclassics',
		['hash'] = `s8d2`,
		['shop'] = 'pdm',
	},
	['760li04'] = {              
		['name'] = 'Bmw 2004 7 serie',
		['brand'] = '',
		['model'] = '760li04',
		['price'] = 40000,
		['category'] = 'sportsclassics',
		['hash'] = `760li04`,
		['shop'] = 'pdm',
	},
	['84rx7k'] = {
		['name'] = 'rx7 fc stance',
		['brand'] = '',
		['model'] = '84rx7k',
		['price'] = 30000,
		['category'] = 'sportsclassics',
		['hash'] = `84rx7k`,
		['shop'] = 'pdm',
	},
	['majfd'] = {
		['name'] = 'rx7 fd',
		['brand'] = '',
		['model'] = 'majfd',
		['price'] = 45000,
		['category'] = 'sportsclassics',
		['hash'] = `majfd`,
		['shop'] = 'pdm',
	},
	['sl500'] = {
		['name'] = 'Mercedes sl500',
		['brand'] = '',
		['model'] = 'sl500',
		['price'] = 35000,
		['category'] = 'sportsclassics',
		['hash'] = `sl500`,
		['shop'] = 'pdm',
	},
	['cheetah2'] = {
		['name'] = 'Cheetah Classic',
		['brand'] = 'Grotti',
		['model'] = 'cheetah2',
		['price'] = 195000,
		['category'] = 'sports',
		['hash'] = `cheetah2`,
		['shop'] = 'luxury',
	},
	['180sx'] = {
		['name'] = 'Nissan 180sx',
		['brand'] = '',
		['model'] = '180sx',
		['price'] = 30000,
		['category'] = 'sportsclassic',
		['hash'] = `180sx`,
		['shop'] = 'pdm',
	},
	['subwrx'] = {							--DLC
		['name'] = 'Subaru Impreza wrx sti',
		['brand'] = '',
		['model'] = 'subwrx',
		['price'] = 30000,
		['category'] = 'sportsclassic',
		['hash'] = `subwrx`,
		['shop'] = 'pdm',
	},
	['mk2100'] = {
		['name'] = 'Totyoto chaser jzx100',
		['brand'] = '',
		['model'] = 'mk2100',
		['price'] = 20000,
		['category'] = 'sportsclassics',
		['hash'] = `mk2100`,
		['shop'] = 'pdm',
	},
	['toysupmk4'] = {							--DLC
		['name'] = 'Toyota supra Mk4',
		['brand'] = '',
		['model'] = 'toysupmk4',
		['price'] = 55000,
		['category'] = 'sportsclassics',
		['hash'] = `toysupmk4`,
		['shop'] = 'pdm',
	},
		--- Super
	['adder'] = {
		['name'] = 'Adder',
		['brand'] = 'Truffade',
		['model'] = 'adder',
		['price'] = 280000,
		['category'] = 'super',
		['hash'] = `adder`,
		['shop'] = 'luxury',
	},
	['autarch'] = {
		['name'] = 'Autarch',
		['brand'] = '�verfl�d',
		['model'] = 'autarch',
		['price'] = 224000,
		['category'] = 'super',
		['hash'] = `autarch`,
		['shop'] = 'luxury',
	},
	['banshee2'] = {
		['name'] = 'Banshee 900R',
		['brand'] = 'Bravado',
		['model'] = 'banshee2',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `banshee2`,
		['shop'] = 'luxury',
	},
	['bullet'] = {
		['name'] = 'Bullet',
		['brand'] = 'Vapid',
		['model'] = 'bullet',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `bullet`,
		['shop'] = 'luxury',
	},
	['cheetah'] = {
		['name'] = 'Cheetah',
		['brand'] = 'Grotti',
		['model'] = 'cheetah',
		['price'] = 214000,
		['category'] = 'super',
		['hash'] = `cheetah`,
		['shop'] = 'luxury',
	},
	['cyclone'] = {         --might be too overpowered
		['name'] = 'Cyclone',
		['brand'] = 'Coil',
		['model'] = 'cyclone',
		['price'] = 300000,
		['category'] = 'super',
		['hash'] = `cyclone`,
		['shop'] = 'luxury',
	},
	['entity2'] = {
		['name'] = 'Entity XXR',
		['brand'] = '�verfl�d',
		['model'] = 'entity2',
		['price'] = 164000,
		['category'] = 'super',
		['hash'] = `entity2`,
		['shop'] = 'luxury',
	},
	['entityxf'] = {
		['name'] = 'Entity XF',
		['brand'] = '�verfl�d',
		['model'] = 'entityxf',
		['price'] = 180000,
		['category'] = 'super',
		['hash'] = `entityxf`,
		['shop'] = 'luxury',
	},
	['emerus'] = {							--DLC
		['name'] = 'Emerus',
		['brand'] = 'Progen',
		['model'] = 'emerus',
		['price'] = 220000,
		['category'] = 'super',
		['hash'] = `emerus`,
		['shop'] = 'luxury',
	},
	['fmj'] = {
		['name'] = 'FMJ',
		['brand'] = 'Vapid',
		['model'] = 'fmj',
		['price'] = 125000,
		['category'] = 'super',
		['hash'] = `fmj`,
		['shop'] = 'luxury',
	},
	['furia'] = {
		['name'] = 'Furia',
		['brand'] = 'Grotti',
		['model'] = 'furia',
		['price'] = 230000,
		['category'] = 'super',
		['hash'] = `furia`,
		['shop'] = 'luxury',
	},
	['gp1'] = {
		['name'] = 'GP1',
		['brand'] = 'Progen',
		['model'] = 'gp1',
		['price'] = 110000,
		['category'] = 'super',
		['hash'] = `gp1`,
		['shop'] = 'luxury',
	},
	['infernus'] = {
		['name'] = 'Infernus',
		['brand'] = 'Pegassi',
		['model'] = 'infernus',
		['price'] = 235000,
		['category'] = 'super',
		['hash'] = `infernus`,
		['shop'] = 'luxury',
	},
	['italigtb'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb',
		['price'] = 170000,
		['category'] = 'super',
		['hash'] = `italigtb`,
		['shop'] = 'luxury',
	},
	['italigtb2'] = {
		['name'] = 'Itali GTB',
		['brand'] = 'Progen',
		['model'] = 'italigtb2',
		['price'] = 250000,
		['category'] = 'super',
		['hash'] = `italigtb2`,
		['shop'] = 'luxury',
	},
	['krieger'] = {							--DLC
		['name'] = 'Krieger',
		['brand'] = 'Benefactor',
		['model'] = 'krieger',
		['price'] = 222000,
		['category'] = 'super',
		['hash'] = `krieger`,
		['shop'] = 'luxury',
	},
	['le7b'] = {
		['name'] = 'RE-7B',
		['brand'] = 'Annis',
		['model'] = 'le7b',
		['price'] = 260000,
		['category'] = 'super',
		['hash'] = `le7b`,
		['shop'] = 'luxury',
	},
	['nero'] = {
		['name'] = 'Nero',
		['brand'] = 'Truffade',
		['model'] = 'nero',
		['price'] = 200000,
		['category'] = 'super',
		['hash'] = `nero`,
		['shop'] = 'luxury',
	},
	['nero2'] = {
		['name'] = 'Nero Custom',
		['brand'] = 'Truffade',
		['model'] = 'nero2',
		['price'] = 260000,
		['category'] = 'super',
		['hash'] = `nero2`,
		['shop'] = 'luxury',
	},
	['osiris'] = {
		['name'] = 'Osiris',
		['brand'] = 'Pegassi',
		['model'] = 'osiris',
		['price'] = 220000,
		['category'] = 'super',
		['hash'] = `osiris`,
		['shop'] = 'luxury',
	},
	['penetrator'] = {
		['name'] = 'Penetrator',
		['brand'] = 'Ocelot',
		['model'] = 'penetrator',
		['price'] = 130000,
		['category'] = 'super',
		['hash'] = `penetrator`,
		['shop'] = 'luxury',
	},
	['pfister811'] = {
		['name'] = '811',
		['brand'] = 'Pfister',
		['model'] = 'pfister811',
		['price'] = 220000,
		['category'] = 'super',
		['hash'] = `pfister811`,
		['shop'] = 'luxury',
	},
	['prototipo'] = {
		['name'] = 'X80 Proto',
		['brand'] = 'Grotti',
		['model'] = 'prototipo',
		['price'] = 235000,
		['category'] = 'super',
		['hash'] = `prototipo`,
		['shop'] = 'luxury',
	},
	['reaper'] = {
		['name'] = 'Reaper',
		['brand'] = 'Pegassi',
		['model'] = 'reaper',
		['price'] = 100000,
		['category'] = 'super',
		['hash'] = `reaper`,
		['shop'] = 'luxury',
	},
	['s80'] = {							--DLC
		['name'] = 'S80RR',
		['brand'] = 'Annis',
		['model'] = 's80',
		['price'] = 205000,
		['category'] = 'super',
		['hash'] = `s80`,
		['shop'] = 'luxury',
	},
	['sc1'] = {
		['name'] = 'SC1',
		['brand'] = '�bermacht',
		['model'] = 'sc1',
		['price'] = 90000,
		['category'] = 'super',
		['hash'] = `sc1`,
		['shop'] = 'luxury',
	},
	['sheava'] = {							--DLC
		['name'] = 'ETR1',
		['brand'] = 'Emperor',
		['model'] = 'sheava',
		['price'] = 220000,
		['category'] = 'super',
		['hash'] = `sheava`,
		['shop'] = 'luxury',
	},
	['sultanrs'] = {
		['name'] = 'Sultan RS',
		['brand'] = 'Karin',
		['model'] = 'sultanrs',
		['price'] = 76500,
		['category'] = 'sports',
		['hash'] = `sultanrs`,
		['shop'] = 'luxury',
	},
	['t20'] = {
		['name'] = 'T20',
		['brand'] = 'Progen',
		['model'] = 't20',
		['price'] = 1650000,
		['category'] = 'super',
		['hash'] = `t20`,
		['shop'] = 'luxury',
	},
	['taipan'] = {
		['name'] = 'Taipan',
		['brand'] = 'Cheval',
		['model'] = 'taipan',
		['price'] = 1850000,
		['category'] = 'super',
		['hash'] = `taipan`,
		['shop'] = 'luxury',
	},
	['tempesta'] = {
		['name'] = 'Tempesta',
		['brand'] = 'Pegassi',
		['model'] = 'tempesta',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `tempesta`,
		['shop'] = 'luxury',
	},
	['tezeract'] = {
		['name'] = 'Tezeract',
		['brand'] = 'Pegassi',
		['model'] = 'tezeract',
		['price'] = 220000,
		['category'] = 'super',
		['hash'] = `tezeract`,
		['shop'] = 'luxury',
	},
	['thrax'] = {							--DLC
		['name'] = 'Thrax',
		['brand'] = 'Truffade',
		['model'] = 'thrax',
		['price'] = 180000,
		['category'] = 'super',
		['hash'] = `thrax`,
		['shop'] = 'luxury',
	},
	['tigon'] = {
		['name'] = 'Tigon',
		['brand'] = 'Lampadati',
		['model'] = 'tigon',
		['price'] = 240000,
		['category'] = 'super',
		['hash'] = `tigon`,
		['shop'] = 'luxury',
	},
	['turismor'] = {
		['name'] = 'Turismo R',
		['brand'] = 'Grotti',
		['model'] = 'turismor',
		['price'] = 140000,
		['category'] = 'super',
		['hash'] = `turismor`,
		['shop'] = 'luxury',
	},
	['tyrant'] = {
		['name'] = 'Tyrant',
		['brand'] = ' �verfl�d',
		['model'] = 'tyrant',
		['price'] = 2100000,
		['category'] = 'super',
		['hash'] = `tyrant`,
		['shop'] = 'luxury',
	},
	['tyrus'] = {
		['name'] = 'Tyrus',
		['brand'] = 'Progen',
		['model'] = 'tyrus',
		['price'] = 230000,
		['category'] = 'super',
		['hash'] = `tyrus`,
		['shop'] = 'luxury',
	},
	['vacca'] = {
		['name'] = 'Vacca',
		['brand'] = 'Pegassi',
		['model'] = 'vacca',
		['price'] = 105000,
		['category'] = 'super',
		['hash'] = `vacca`,
		['shop'] = 'luxury',
	},
	['vagner'] = {
		['name'] = 'Vagner',
		['brand'] = 'Dewbauchee',
		['model'] = 'vagner',
		['price'] = 1660000,
		['category'] = 'super',
		['hash'] = `vagner`,
		['shop'] = 'luxury',
	},
	['visione'] = {
		['name'] = 'Visione',
		['brand'] = 'Grotti',
		['model'] = 'visione',
		['price'] = 750000,
		['category'] = 'sports',
		['hash'] = `visione`,
		['shop'] = 'luxury',
	},
	['voltic'] = {
		['name'] = 'Voltic',
		['brand'] = 'Coil',
		['model'] = 'voltic',
		['price'] = 120000,
		['category'] = 'super',
		['hash'] = `voltic`,
		['shop'] = 'luxury',
	},
	['voltic2'] = {
		['name'] = 'Rocket Voltic',
		['brand'] = 'Coil',
		['model'] = 'voltic2',
		['price'] = 9830400,
		['category'] = 'super',
		['hash'] = `voltic2`,
		['shop'] = 'luxury',
	},
	['xa21'] = {
		['name'] = 'XA-21',
		['brand'] = 'Ocelot',
		['model'] = 'xa21',
		['price'] = 180000,
		['category'] = 'super',
		['hash'] = `xa21`,
		['shop'] = 'luxury',
	},
	['zentorno'] = {
		['name'] = 'Zentorno',
		['brand'] = 'Pegassi',
		['model'] = 'zentorno',
		['price'] = 340000,
		['category'] = 'super',
		['hash'] = `zentorno`,
		['shop'] = 'luxury',
	},
	['zorrusso'] = {							--DLC
		['name'] = 'Zorrusso',
		['brand'] = 'Pegassi',
		['model'] = 'zorrusso',
		['price'] = 277000,
		['category'] = 'super',
		['hash'] = `zorrusso`,
		['shop'] = 'luxury',
	},
	-- Vans
		-- Utility
						-- Boats
	['squalo'] = {
		['name'] = 'Squalo',
		['brand'] = 'Shitzu',
		['model'] = 'squalo',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `squalo`,
		['shop'] = 'boats',
	},
	['marquis'] = {
		['name'] = 'Marquis',
		['brand'] = 'Dinka',
		['model'] = 'marquis',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `marquis`,
		['shop'] = 'boats',
	},
	['seashark'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark`,
		['shop'] = 'boats',
	},
	['seashark2'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark2`,
		['shop'] = 'boats',
	},
	['seashark3'] = {
		['name'] = 'Seashark',
		['brand'] = 'Speedophile',
		['model'] = 'seashark3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `seashark3`,
		['shop'] = 'boats',
	},
	['jetmax'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Jetmax',
		['model'] = 'jetmax',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `jetmax`,
		['shop'] = 'boats',
	},
	['tropic'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic`,
		['shop'] = 'boats',
	},
	['tropic2'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Tropic',
		['model'] = 'tropic2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `tropic2`,
		['shop'] = 'boats',
	},
	['dinghy'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy`,
		['shop'] = 'boats',
	},
	['dinghy2'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy2`,
		['shop'] = 'boats',
	},
	['dinghy3'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy3',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy3`,
		['shop'] = 'boats',
	},
	['dinghy4'] = {
		['name'] = 'Nagasaki',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy4',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `dinghy4`,
		['shop'] = 'boats',
	},
	['suntrap'] = {
		['name'] = 'Shitzu',
		['brand'] = 'Suntrap',
		['model'] = 'suntrap',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `suntrap`,
		['shop'] = 'boats',
	},
	['speeder'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder`,
		['shop'] = 'boats',
	},
	['speeder2'] = {
		['name'] = 'Speeder',
		['brand'] = 'Pegassi',
		['model'] = 'speeder2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `speeder2`,
		['shop'] = 'boats',
	},
	['longfin'] = {
		['name'] = 'Longfin',
		['brand'] = 'Shitzu',
		['model'] = 'longfin',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `longfin`,
		['shop'] = 'boats',
	},
	['toro'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro`,
		['shop'] = 'boats',
	},
	['toro2'] = {
		['name'] = 'Toro',
		['brand'] = 'Lampadati',
		['model'] = 'toro2',
		['price'] = 40000,
		['category'] = 'boats',
		['hash'] = `toro2`,
		['shop'] = 'boats',
	},
	-- helicopters
	['buzzard2'] = {
		['name'] = 'Buzzard',
		['brand'] = 'Unknown',
		['model'] = 'buzzard2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `buzzard2`,
		['shop'] = 'air',
	},
	['frogger'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger`,
		['shop'] = 'air',
	},
	['frogger2'] = {
		['name'] = 'Frogger',
		['brand'] = 'Unknown',
		['model'] = 'frogger2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `frogger2`,
		['shop'] = 'air',
	},
	['maverick'] = {
		['name'] = 'Maverick',
		['brand'] = 'Unknown',
		['model'] = 'maverick',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `maverick`,
		['shop'] = 'air',
	},
	['swift'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift`,
		['shop'] = 'air',
	},
	['swift2'] = {
		['name'] = 'Swift',
		['brand'] = 'Buckingham',
		['model'] = 'swift2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `swift2`,
		['shop'] = 'air',
	},
	['seasparrow'] = {
		['name'] = 'Sea Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow`,
		['shop'] = 'air',
	},
	['seasparrow2'] = {
		['name'] = 'Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow2`,
		['shop'] = 'air',
	},
	['seasparrow3'] = {
		['name'] = 'Sparrow',
		['brand'] = 'Unknown',
		['model'] = 'seasparrow3',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `seasparrow3`,
		['shop'] = 'air',
	},
	['supervolito'] = {
		['name'] = 'SuperVolito',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito`,
		['shop'] = 'air',
	},
	['supervolito2'] = {
		['name'] = 'SuperVolito Carbon',
		['brand'] = 'Buckingham',
		['model'] = 'supervolito2',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `supervolito2`,
		['shop'] = 'air',
	},
	['volatus'] = {
		['name'] = 'Volatus',
		['brand'] = 'Buckingham',
		['model'] = 'volatus',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `volatus`,
		['shop'] = 'air',
	},
	['havok'] = {
		['name'] = 'Havok',
		['brand'] = 'Nagasaki',
		['model'] = 'havok',
		['price'] = 52000,
		['category'] = 'helicopters',
		['hash'] = `havok`,
		['shop'] = 'air',
	},
	-- Planes
	['duster'] = {
		['name'] = 'Duster',
		['brand'] = 'Unknown',
		['model'] = 'duster',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `duster`,
		['shop'] = 'air',
	},
	['luxor'] = {
		['name'] = 'Luxor',
		['brand'] = 'Buckingham',
		['model'] = 'luxor',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `luxor`,
		['shop'] = 'air',
	},
	['luxor2'] = {
		['name'] = 'Luxor Deluxe',
		['brand'] = 'Buckingham',
		['model'] = 'luxor2',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `luxor2`,
		['shop'] = 'air',
	},
	['stunt'] = {
		['name'] = 'Mallard',
		['brand'] = 'Unknown',
		['model'] = 'stunt',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `stunt`,
		['shop'] = 'air',
	},
	['mammatus'] = {
		['name'] = 'Mammatus',
		['brand'] = 'Unknown',
		['model'] = 'mammatus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `mammatus`,
		['shop'] = 'air',
	},
	['velum'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `velum`,
		['shop'] = 'air',
	},
	['velum2'] = {
		['name'] = 'Velum',
		['brand'] = 'Unknown',
		['model'] = 'velum2',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `velum2`,
		['shop'] = 'air',
	},
	['shamal'] = {
		['name'] = 'Shamal',
		['brand'] = 'Buckingham',
		['model'] = 'shamal',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `shamal`,
		['shop'] = 'air',
	},
	['vestra'] = {
		['name'] = 'Vestra',
		['brand'] = 'Buckingham',
		['model'] = 'vestra',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `vestra`,
		['shop'] = 'air',
	},
	['dodo'] = {
		['name'] = 'Dodo',
		['brand'] = 'Mammoth',
		['model'] = 'dodo',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `dodo`,
		['shop'] = 'air',
	},
	['howard'] = {
		['name'] = 'Howard NX-25',
		['brand'] = 'Buckingham',
		['model'] = 'howard',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `howard`,
		['shop'] = 'air',
	},
	['alphaz1'] = {
		['name'] = 'Alpha-Z1',
		['brand'] = 'Buckingham',
		['model'] = 'alphaz1',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `alphaz1`,
		['shop'] = 'air',
	},
	['nimbus'] = {
		['name'] = 'Nimbus',
		['brand'] = 'Buckingham',
		['model'] = 'nimbus',
		['price'] = 45000,
		['category'] = 'planes',
		['hash'] = `nimbus`,
		['shop'] = 'air',
	},
 }
for k,v in pairs(QBShared.Vehicles) do
	QBShared.VehicleHashes[v.hash] = v
end
